In [1]:
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
#reading in Eugene emergency response data 2015-2025

CAD2015 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2015noloc.csv",na_values='NULL')
CAD2016 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2016noloc.csv",na_values='NULL')
CAD2017 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2017noloc.csv",na_values='NULL')
CAD2018 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2018noloc.csv",na_values='NULL')
CAD2019 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2019noloc.csv",na_values='NULL')
CAD2020 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2020noloc.csv",na_values='NULL')
CAD2021 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2021noloc.csv",na_values='NULL')
CAD2022 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2022noloc.csv",na_values='NULL')
CAD2023 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2023noloc.csv",na_values='NULL')
CAD2024 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2024noloc.csv",na_values='NULL')
CAD2025 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2025noloc.csv",na_values='NULL')

/var/folders/0y/gklqyv_101130y1ly46wc5wm0000gn/T/ipykernel_83205/2484449190.py:9: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  CAD2021 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2021noloc.csv",na_values='NULL')
/var/folders/0y/gklqyv_101130y1ly46wc5wm0000gn/T/ipykernel_83205/2484449190.py:13: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  CAD2025 = pd.read_csv("data/Eugene_CAD_data_noloc/EugeneCAD2025noloc.csv",na_values='NULL')

In [3]:
#putting all Eug data frames 2015-25 into a single data frame
frames = [CAD2015, CAD2016, CAD2017, CAD2018, CAD2019, CAD2020,
          CAD2021, CAD2022, CAD2023, CAD2024, CAD2025]

EUG = pd.concat(frames)
EUG

,yr,agency,service,inci_id,calltime,case_id,callsource,nature,closecode,closed_as,secs_to_disp,secs_to_arrv,secs_to_close,disp,arrv,priority,primeunit,units_dispd,units_arrived,month
0,2015,EPD,LAW,15000001,2015-01-01 00:00:00.000,NaN,SELF,PERSON STOP,ASST,ASSISTED,0.0,0.0,217,1,1,6,_5E48,1,1,NaN
1,2015,EPD,LAW,15000002,2015-01-01 00:00:44.000,NaN,SELF,FIGHT,RSLV,RESOLVED,0.0,0.0,2114,1,1,P,_3F65,4,2,NaN
2,2015,EPD,LAW,15000003,2015-01-01 00:01:05.000,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,708.0,1094.0,1538,1,1,5,_3J79,1,1,NaN
3,2015,EPD,LAW,15000007,2015-01-01 00:03:16.000,NaN,W911,SHOTS FIRED,PCHK,PATROL CHECK,277.0,576.0,891,1,1,3,_5E48,2,2,NaN
4,2015,EPD,LAW,15000010,2015-01-01 00:03:34.000,NaN,SELF,ILLEGAL FIREWORKS,ADVI,ADVISED,0.0,0.0,150,1,1,5,_5K97,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117347,2025,EPD,LAW,25327368,2025-12-31 23:39:12.000,NaN,SELF,TRAFFIC STOP,SBCK,SOBRIETY CHECK,0.0,0.0,338,1,1,6,_4U41,1,1,12.0
117348,2025,EPD,LAW,25327370,2025-12-31 23:40:48.000,NaN,SELF,TRAFFIC STOP,UTC,UNIFORM TRAFFIC CITATION ISSUED,1.0,1.0,478,1,1,6,_5E56,2,2,12.0
117349,2025,EPD,LAW,25327374,2025-12-31 23:45:57.000,NaN,SELF,PATROL CHECK,UTC,UNIFORM TRAFFIC CITATION ISSUED,0.0,0.0,946,1,1,6,_4E48,3,3,12.0
117350,2025,EPD,LAW,25327376,2025-12-31 23:49:12.000,NaN,SELF,ASSIST OREGON STATE POLICE,ASST,ASSISTED,0.0,0.0,765,1,1,P,_5T81,1,1,12.0
117351,2025,EPD,LAW,25327378,2025-12-31 23:56:03.000,NaN,E911,SUSPICIOUS CONDITIONS,PCHK,PATROL CHECK,670.0,670.0,944,1,1,3,_5E56,1,1,12.0

In [4]:
#Converting data strings to datetime objects
EUG['calltime'] = EUG['calltime'].apply(
    lambda x: dt.datetime.strptime(x,'%Y-%m-%d %H:%M:%S.%f'))

In [5]:
#checking for duplicated rows
sum(EUG.duplicated())
#according to this, there are none

0

In [6]:
#creating month and year columns
EUG['month'] = EUG['calltime'].dt.month
EUG['year'] = EUG['calltime'].dt.year

In [7]:
#Strip whitespace and leading "_" from the primeunit column
EUG['primeunit'] = EUG['primeunit'].str.strip()
EUG['primeunit'] = EUG['primeunit'].str.strip("_")

In [8]:
#dropping rows where the primeunit is a null value and more than 0 units were dispatched
EUG = EUG[(EUG['primeunit'].notna()) | (EUG['units_dispd'] == 0)]

In [9]:
#creating an institution column
EUG["Institution"] = np.where(    
    EUG["primeunit"].str.contains("J|CAH", na=False),    
    "CAHOOTS",    
    np.where(        
        EUG["primeunit"].isna(),        
        "Neither",        
        "EPD"    
    )
)

/var/folders/0y/gklqyv_101130y1ly46wc5wm0000gn/T/ipykernel_83205/3975195290.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EUG["Institution"] = np.where(

In [10]:
#dropping unneeded columns
EUG.drop(['agency','service','yr','case_id'],axis=1,inplace=True)

/var/folders/0y/gklqyv_101130y1ly46wc5wm0000gn/T/ipykernel_83205/3663530669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EUG.drop(['agency','service','yr','case_id'],axis=1,inplace=True)

In [11]:
EUG

,inci_id,calltime,callsource,nature,closecode,closed_as,secs_to_disp,secs_to_arrv,secs_to_close,disp,arrv,priority,primeunit,units_dispd,units_arrived,month,year,Institution
0,15000001,2015-01-01 00:00:00,SELF,PERSON STOP,ASST,ASSISTED,0.0,0.0,217,1,1,6,5E48,1,1,1,2015,EPD
1,15000002,2015-01-01 00:00:44,SELF,FIGHT,RSLV,RESOLVED,0.0,0.0,2114,1,1,P,3F65,4,2,1,2015,EPD
2,15000003,2015-01-01 00:01:05,PHONE,CHECK WELFARE,ASST,ASSISTED,708.0,1094.0,1538,1,1,5,3J79,1,1,1,2015,CAHOOTS
3,15000007,2015-01-01 00:03:16,W911,SHOTS FIRED,PCHK,PATROL CHECK,277.0,576.0,891,1,1,3,5E48,2,2,1,2015,EPD
4,15000010,2015-01-01 00:03:34,SELF,ILLEGAL FIREWORKS,ADVI,ADVISED,0.0,0.0,150,1,1,5,5K97,1,1,1,2015,EPD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117347,25327368,2025-12-31 23:39:12,SELF,TRAFFIC STOP,SBCK,SOBRIETY CHECK,0.0,0.0,338,1,1,6,4U41,1,1,12,2025,EPD
117348,25327370,2025-12-31 23:40:48,SELF,TRAFFIC STOP,UTC,UNIFORM TRAFFIC CITATION ISSUED,1.0,1.0,478,1,1,6,5E56,2,2,12,2025,EPD
117349,25327374,2025-12-31 23:45:57,SELF,PATROL CHECK,UTC,UNIFORM TRAFFIC CITATION ISSUED,0.0,0.0,946,1,1,6,4E48,3,3,12,2025,EPD
117350,25327376,2025-12-31 23:49:12,SELF,ASSIST OREGON STATE POLICE,ASST,ASSISTED,0.0,0.0,765,1,1,P,5T81,1,1,12,2025,EPD
117351,25327378,2025-12-31 23:56:03,E911,SUSPICIOUS CONDITIONS,PCHK,PATROL CHECK,670.0,670.0,944,1,1,3,5E56,1,1,12,2025,EPD

In [12]:
#Exporting cleaned Eugene daca
EUG.to_csv("./data/EUG_cleaned.csv")