In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
welfare = pd.read_csv("data/welfare.csv",na_values='NULL')

In [3]:
welfare.head()

,Unnamed: 0,inci_id,calltime,case_id,callsource,nature,closecode,closed_as,secs_to_disp,secs_to_arrv,secs_to_close,disp,arrv,priority,primeunit,units_dispd,units_arrived,month,year,Institution
0,0,15000003,2015-01-01 00:01:05,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,708.0,1094.0,1538,1,1,5,3J79,1,1,1,2015,CAHOOTS
1,1,15000052,2015-01-01 00:38:37,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,2402.0,2941.0,3594,1,1,5,3J79,1,1,1,2015,CAHOOTS
2,2,15000092,2015-01-01 01:28:40,NaN,PHONE,CHECK WELFARE,UTL,UNABLE TO LOCATE,1305.0,1524.0,1824,1,1,5,5B44,1,1,1,2015,EPD
3,3,15000107,2015-01-01 01:41:40,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,600.0,926.0,1285,1,1,5,3J79,1,1,1,2015,CAHOOTS
4,4,15000435,2015-01-01 15:09:21,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,3018.0,3605.0,4369,1,1,7,3J79,1,1,1,2015,CAHOOTS

In [4]:
calls = welfare.groupby(['year','month','Institution'])['closed_as'].count()
calls

year  month  Institution
2015  1      CAHOOTS        138
             EPD            164
             Neither         23
      2      CAHOOTS        154
             EPD            148
                           ...
2025  10     Neither        144
      11     EPD            336
             Neither        112
      12     EPD            400
             Neither         82
Name: closed_as, Length: 374, dtype: int64

In [5]:
calldf = calls.to_frame()

In [6]:
calldf.reset_index()

     year  month Institution  closed_as
0    2015      1     CAHOOTS        138
1    2015      1         EPD        164
2    2015      1     Neither         23
3    2015      2     CAHOOTS        154
4    2015      2         EPD        148
..    ...    ...         ...        ...
369  2025     10     Neither        144
370  2025     11         EPD        336
371  2025     11     Neither        112
372  2025     12         EPD        400
373  2025     12     Neither         82

[374 rows x 4 columns]

In [11]:
#calldf['date'] = pd.to_datetime(calldf[['month','year']].assign(DAY=1))

In [12]:
calldf.index

MultiIndex([(2015,  1, 'CAHOOTS'),
            (2015,  1,     'EPD'),
            (2015,  1, 'Neither'),
            (2015,  2, 'CAHOOTS'),
            (2015,  2,     'EPD'),
            (2015,  2, 'Neither'),
            (2015,  3, 'CAHOOTS'),
            (2015,  3,     'EPD'),
            (2015,  3, 'Neither'),
            (2015,  4, 'CAHOOTS'),
            ...
            (2025,  8,     'EPD'),
            (2025,  8, 'Neither'),
            (2025,  9,     'EPD'),
            (2025,  9, 'Neither'),
            (2025, 10,     'EPD'),
            (2025, 10, 'Neither'),
            (2025, 11,     'EPD'),
            (2025, 11, 'Neither'),
            (2025, 12,     'EPD'),
            (2025, 12, 'Neither')],
           names=['year', 'month', 'Institution'], length=374)

In [10]:
#you've got a multi-index df. Need to change that to columns. Start there. 
#After that, you'll be able to graph it the way you want to